#!/bin/bash
echo "Setting up Mailgun environment variables..."
echo ""
echo "Run these commands to configure Mailgun:"
echo ""
echo "export EMAIL_PROVIDER=\"mailgun\""
echo "export MAILGUN_API_KEY=\"your_mailgun_api_key_here\""
echo "export MAILGUN_DOMAIN=\"your_mailgun_domain_here\""
echo "export APP_URL=\"http://localhost:3000\""
echo ""
echo "For testing with sandbox domain:"
echo "export MAILGUN_DOMAIN=\"sandbox-xxxxx.mailgun.org\""
echo ""
echo "For production with your domain:"
echo "export MAILGUN_DOMAIN=\"yourdomain.com\""
